name = "daily-timesheet"
compatibility_date = "2026-07-01"

[[d1_databases]]
binding = "DB"
database_name = "daily-timesheet-db"
# Run `npx wrangler d1 create daily-timesheet-db` and paste the Database ID here.
database_id = "085798c6-6dfe-47ef-bcc6-9a3ac6d7f52b"
